# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'VS2017-Win2016'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: DownloadSecureFile@1
  displayName: 'Download EETLauncher.snk'
  inputs:
    secureFile: 'c89db732-03b6-4510-9279-b19f6727114f'

- task: DownloadSecureFile@1
  displayName: 'Download EETLauncherWPF_TemporaryKey.pfx'
  inputs:
    secureFile: '9340e48d-8bb0-4cc8-b241-80f08b9d9616'

- powershell: 'Import-PfxCertificate -FilePath D:\a\_temp\EETLauncherWPF_TemporaryKey.pfx -CertStoreLocation Cert:\CurrentUser\My'
  failOnStderr: true
  displayName: 'PowerShell - Cert'

- task: VSBuild@1
  displayName: 'Build solution **\*.sln'
  inputs:
    solution: '$(Parameters.solution)'
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'
    msbuildArchitecture: x64

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**\bin\$(BuildConfiguration)\**'
    TargetFolder: '$(build.artifactstagingdirectory)'
    OverWrite: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'

- powershell: |
   function New-Wait { param ($arg)
       Write-Output "Waiting $arg seconds..."
       [System.Threading.Thread]::Sleep($arg*1000)
   }
   Set-Alias -Name Wait -Value New-Wait
   
   cd $(build.artifactstagingdirectory)
   
   New-Item -ItemType Directory -Name Temp | Out-Null
   Wait 1
   Set-Location Temp
   git init
   Wait 1
   git config user.email "alienquake@hotmail.com"
   git config user.name "ALIENQuake"
   Wait 1
   git remote add origin "https://alienquake:$(pass)@github.com/ALIENQuake/EETLauncher.git" | Out-Null
   Wait 1
   git pull origin master --quiet | Out-Null
   Wait 1
   Copy-Item -Path D:\a\1\a\$($env:BUILD_DEFINITIONNAME)\bin\Release\EETLauncher.exe | Out-Null
   Wait 1
   git add . | Out-Null
   Wait 1
   git commit -m "Add files via upload" | Out-Null
   Wait 1
   git push origin master --quiet
   
   # Use the environment variables input below to pass secret variables to this script.
  failOnStderr: true
  displayName: 'PowerShell - Upload to Github.com/EETLauncher'
