name: build

on:
  workflow_dispatch:
  push:
    tags: [ "*.*.*" ]

jobs:
  build:
    runs-on: windows-2019
    permissions: write-all
    steps:
      
      - name: Checkout Source
        uses: actions/checkout@v4.2.2

      - name: Setup NuGet.exe for use with actions
        uses: NuGet/setup-nuget@v2.0.0

      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v2

      - name: EETLauncher_snk
        env:
          EETLauncher_snk: ${{ secrets.EETLauncher_snk }}
        run: |
          Set-Content -Path "EETLauncher/EETLauncher.snk" -Value ([System.Convert]::FromBase64String($env:EETLauncher_snk)) -AsByteStream
        
      - name: EETLauncher_TemporaryKey_pfx
        env:
          EETLauncher_TemporaryKey_pfx: ${{ secrets.EETLauncher_TemporaryKey_pfx }}
        run: |
          Set-Content -Path "EETLauncher/EETLauncher_TemporaryKey.pfx" -Value ([System.Convert]::FromBase64String($env:EETLauncher_TemporaryKey_pfx)) -AsByteStream
     
      - name: Import-PfxCertificate
        run: |
          Import-PfxCertificate -FilePath "${{ github.workspace }}/EETLauncher/EETLauncher_TemporaryKey.pfx" -CertStoreLocation Cert:/CurrentUser/My
      
      - name: Restore Packages
        run: nuget restore EETLauncher/EETLauncherWPF.csproj
      
      - name: Build solution
        run: msbuild EETLauncher/EETLauncherWPF.csproj -property:Configuration=Release

      - name: EETLauncher.exe artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: EETLauncher
          path: ${{ github.workspace }}/EETLauncher/bin/Release/net48/EETLauncher.exe
      
      - name: Checkout Destination
        uses: actions/checkout@v4.2.2
        with: 
          repository: ALIENQuake/EETLauncher
          ssh-key: ${{ secrets.ALIENQUAKE_EETLAUNCHER_SSH_KEY }}
          path: Destination

      - name: Create file
        run: |
          Copy-Item -Path "${{ github.workspace }}/EETLauncher/bin/Release/net48/EETLauncher.exe"
        working-directory: Destination

      - name: Get-Childitem -Recurse at Destination
        run: |
          Get-Childitem -Recurse
        working-directory: Destination

      # - name: Push Destination
      #   run: |
      #     git add .
      #     git config user.email "alienquake@hotmail.com"
      #     git config user.name "ALIENQuake"
      #     git commit -am "Add files via upload"
      #     git push
      #   working-directory: Destination
      
      - name: Finish
        run: echo Finish
        
