name: build

on:
  workflow_dispatch:
  push:
    tags: [ "*.*.*" ]

jobs:
  build:
    runs-on: windows-2019
    permissions: write-all
    steps:
      
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Setup NuGet.exe for use with actions
        uses: NuGet/setup-nuget@v2.0.0

      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v2

      - name: EETLauncher_snk
        env:
          EETLauncher_snk: ${{ secrets.EETLauncher_snk }}
        run: |
          Set-Content -Path "EETLauncher/EETLauncher.snk" -Value ([System.Convert]::FromBase64String($env:EETLauncher_snk)) -AsByteStream
        
      - name: EETLauncher_TemporaryKey_pfx
        env:
          EETLauncher_TemporaryKey_pfx: ${{ secrets.EETLauncher_TemporaryKey_pfx }}
        run: |
          Set-Content -Path "EETLauncher\EETLauncher_TemporaryKey.pfx" -Value ([System.Convert]::FromBase64String($env:EETLauncher_TemporaryKey_pfx)) -AsByteStream
        
      - name: Get-Childitem -Recurse
        run: |
          Get-Childitem -Recurse
      
      - name: Import-PfxCertificate
        run: |
          Import-PfxCertificate -FilePath "$env:GITHUB_WORKSPACE\Source\EETLauncher\EETLauncher_TemporaryKey.pfx" -CertStoreLocation Cert:\CurrentUser\My
      
      - name: Restore Packages
        run: nuget restore EETLauncher/EETLauncherWPF.csproj
      
      - name: Build solution
        run: msbuild EETLauncher/EETLauncherWPF.csproj -property:Configuration=Release
        
      # - name: Checkout Destination
      #   uses: actions/checkout@v3
      #   with: 
      #     repository: ALIENQuake/EETLauncher
      #     ssh-key: ${{ secrets.ALIENQUAKE_EETLAUNCHER_SSH_KEY }}
      #     path: Destination

      # - name: Create file
      #   run: |
      #     Copy-Item -Path "$env:GITHUB_WORKSPACE\Source\EETLauncher\bin\Release\EETLauncher.exe"
      #     #Get-Item -Path "$env:GITHUB_WORKSPACE\Source\EETLauncher\bin\Release\EETLauncher.exe"
      #   working-directory: Destination
        
      # - name: Push Destination
      #   run: |
      #     git add .
      #     git config user.email "alienquake@hotmail.com"
      #     git config user.name "ALIENQuake"
      #     git commit -am "Add files via upload"
      #     git push
      #   working-directory: Destination

      # - name: EETLauncher.exe artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: EETLauncher.zip
      #     path: D:/a/EETLauncher-WPF-RUIC/EETLauncher-WPF-RUIC/Source/EETLauncher/bin/Release/EETLauncher.exe
      
      # - name: Finish
      #   run: echo Finish
        
