name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1.1

      - name: EETLauncher_snk
        env:
          EETLauncher_snk: ${{ secrets.EETLauncher_snk }}
        run: |
          Set-Content -Path "EETLauncher/ETLauncher.snk" -Value ([System.Convert]::FromBase64String($env:EETLauncher_snk)) -AsByteStream
      
      - name: EETLauncherWPF_TemporaryKey_pfx
        env:
          EETLauncher_snk: ${{ secrets.EETLauncherWPF_TemporaryKey_pfx }}
        run: |
          Set-Content -Path "EETLauncher/EETLauncherWPF_TemporaryKey.pfx" -Value ([System.Convert]::FromBase64String($env:EETLauncherWPF_TemporaryKey_pfx)) -AsByteStream

      - name: Get-Childitem -Recurse
        run: |
          Get-Childitem -Recurse
      
      - name: Import-PfxCertificate
        run: |
          Import-PfxCertificate -FilePath D:\a\EETLauncher-WPF\EETLauncher-WPF\EETLauncherWPF_TemporaryKey.pfx -CertStoreLocation Cert:\CurrentUser\My
      
      - name: Restore Packages
        run: nuget restore EETLauncher/EETLauncherWPF.csproj

      - name: Build solution
        run: msbuild EETLauncher/EETLauncherWPF.csproj -property:Configuration=Release
