name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1.1
      
      - name: Run
        run: |
          ls
      - name: EETLauncher_snk
        env:
          EETLauncher_snk: ${{ secrets.EETLauncher_snk }}
        run: |
          [Text.Encoding]::Utf8.GetString([Convert]::FromBase64String("$env:EETLauncher_snk")) > "EETLauncher/EETLauncher.snk"
      - name: EETLauncherWPF_TemporaryKey_pfx
        env:
          EETLauncher_snk: ${{ secrets.EETLauncherWPF_TemporaryKey_pfx }}
        run: |
          [Text.Encoding]::Utf8.GetString([Convert]::FromBase64String("$env:EETLauncherWPF_TemporaryKey_pfx")) > "EETLauncher/EETLauncherWPF_TemporaryKey.pfx"
      - name: Restore Packages
        run: nuget restore EETLauncher/EETLauncherWPF.csproj

      - name: Build solution
        run: msbuild EETLauncher/EETLauncherWPF.csproj -property:Configuration=Release
